spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gestionStockLbv?createDatabaseIfNotExist=true&userSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver
## Specify DBMS
  jpa:
    database: MYSQL
    show-sql: false
    generate-ddl: true
# Hibernate DDL Auto (create, create-drop, update)
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8082
